DELETE FROM schemes;

INSERT IGNORE INTO schemes (name, ministry, description, min_age, max_age, max_income, eligible_gender, eligible_castes, eligible_states, eligible_occupations, apply_url, is_active, start_date, end_date, required_documents, benefits, application_mode, application_process) VALUES

-- AGRICULTURE SCHEMES
('PM-KISAN', 'Ministry of Agriculture', 'Pradhan Mantri Kisan Samman Nidhi - income support for farmers', 18, null, 200000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'FARMER', 'https://pmkisan.gov.in', true, '2019-02-01', null, 'Aadhaar Card,Bank Passbook,Khasra/Khatauni Land Record,Mobile Number', 'Rs 6000 per year in 3 installments of Rs 2000 directly in bank account', 'BOTH', 'Visit nearest CSC center or apply on pmkisan.gov.in'),

('PM Fasal Bima Yojana', 'Ministry of Agriculture', 'Crop insurance against natural calamities pests and diseases', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'FARMER', 'https://pmfby.gov.in', true, '2016-01-13', null, 'Aadhaar Card,Land Record,Bank Passbook,Sowing Certificate', 'Compensation for crop loss at very low premium - 2% for Kharif 1.5% for Rabi crops', 'BOTH', 'Apply through bank or insurance company before sowing season'),

('Kisan Credit Card', 'Ministry of Agriculture', 'Short term credit for crop cultivation at low interest', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'FARMER', 'https://pmkisan.gov.in', true, '1998-08-01', null, 'Aadhaar Card,Land Record,Passport Photo,Bank Account', 'Credit up to Rs 3 lakh at 4% interest rate after subvention', 'OFFLINE', 'Visit nearest bank branch with land documents'),

('PM Kisan Maandhan Yojana', 'Ministry of Agriculture', 'Pension scheme for small and marginal farmers', 18, 40, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'FARMER', 'https://pmkmy.gov.in', true, '2019-08-12', null, 'Aadhaar Card,Bank Passbook,Land Record,Mobile Number', 'Rs 3000 per month pension after age 60', 'BOTH', 'Enroll at nearest CSC center'),

('Paramparagat Krishi Vikas Yojana', 'Ministry of Agriculture', 'Support for organic farming', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'FARMER', 'https://pgsindia-ncof.gov.in', true, '2015-01-01', null, 'Aadhaar Card,Land Record,Bank Passbook', 'Rs 50000 per hectare for 3 years for organic farming', 'OFFLINE', 'Contact local agriculture department'),

-- HEALTH SCHEMES
('Ayushman Bharat PMJAY', 'Ministry of Health', 'Free health insurance for low income families', 0, null, 500000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmjay.gov.in', true, '2018-09-23', null, 'Aadhaar Card,Ration Card,Income Certificate', 'Free treatment up to Rs 5 lakh per family per year at 25000+ empanelled hospitals', 'OFFLINE', 'Visit nearest empanelled hospital with Aadhaar card'),

('Ayushman Bharat Senior Citizens', 'Ministry of Health', 'Free health coverage for all senior citizens above 70', 70, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmjay.gov.in', true, '2024-10-29', null, 'Aadhaar Card,Age Proof', 'Free health coverage up to Rs 5 lakh per year regardless of income', 'ONLINE', 'Register on pmjay.gov.in with Aadhaar'),

('Janani Suraksha Yojana', 'Ministry of Health', 'Cash assistance for pregnant women for institutional delivery', 19, null, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://nhm.gov.in', true, '2005-04-12', null, 'Aadhaar Card,BPL Card,JSY Card from ANM', 'Rs 1400 in rural areas Rs 1000 in urban areas cash assistance after delivery', 'OFFLINE', 'Register with ASHA worker or ANM during pregnancy'),

('PM Surakshit Matritva Abhiyan', 'Ministry of Health', 'Free antenatal checkup on 9th of every month', 18, null, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmsma.nhm.gov.in', true, '2016-06-09', null, 'Aadhaar Card,Pregnancy proof', 'Free comprehensive antenatal checkup blood test ultrasound on 9th of every month', 'OFFLINE', 'Visit nearest government health facility on 9th of month'),

-- EDUCATION SCHEMES
('Post Matric SC Scholarship', 'Ministry of Social Justice', 'Scholarship for SC students at post matriculation level', 15, 30, 250000, 'ALL', 'SC', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2022-07-01', '2026-10-31', 'Aadhaar Card,Caste Certificate,Income Certificate,Previous Marksheet,Bank Passbook,Bonafide Certificate', 'Full tuition fee plus maintenance allowance Rs 380-1200 per month', 'ONLINE', 'Apply on scholarships.gov.in before October 31'),

('Post Matric ST Scholarship', 'Ministry of Tribal Affairs', 'Scholarship for ST students at post matriculation level', 15, 30, 250000, 'ALL', 'ST', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2022-07-01', '2026-10-31', 'Aadhaar Card,Caste Certificate,Income Certificate,Previous Marksheet,Bank Passbook,Bonafide Certificate', 'Full tuition fee plus maintenance allowance', 'ONLINE', 'Apply on scholarships.gov.in before October 31'),

('Post Matric OBC Scholarship', 'Ministry of Social Justice', 'Scholarship for OBC students at post matriculation level', 15, 30, 300000, 'ALL', 'OBC', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2022-07-01', '2026-10-31', 'Aadhaar Card,OBC Certificate,Income Certificate,Previous Marksheet,Bank Passbook', 'Tuition fee and maintenance allowance for post matric education', 'ONLINE', 'Apply on scholarships.gov.in'),

('National Means Cum Merit Scholarship', 'Ministry of Education', 'Scholarship for meritorious students from economically weaker sections', 13, 18, 350000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2008-05-15', null, 'Aadhaar Card,Income Certificate,Class 7 Marksheet,Bank Passbook', 'Rs 12000 per year for class 9 to 12 students', 'ONLINE', 'Apply after qualifying NMMS exam'),

('Central Sector Scholarship', 'Ministry of Education', 'Scholarship for students in top 20 percentile of class 12', 17, 25, 800000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2008-01-01', null, 'Aadhaar Card,Class 12 Marksheet,Income Certificate,Bank Passbook,Admission Letter', 'Rs 12000 per year for UG Rs 20000 per year for PG', 'ONLINE', 'Apply on scholarships.gov.in within 3 months of admission'),

('PM Vidya Lakshmi', 'Ministry of Education', 'Education loan at subsidized interest for higher education', 18, 35, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://vidyalakshmi.co.in', true, '2015-08-15', null, 'Aadhaar Card,Admission Letter,Academic Records,Income Certificate', 'Education loans up to Rs 7.5 lakh without collateral at subsidized rates', 'ONLINE', 'Apply on vidyalakshmi.co.in and choose from multiple banks'),

('Ishan Uday Scholarship NE', 'Ministry of Education', 'Special scholarship for students from North East region', 17, 30, 600000, 'ALL', 'SC,ST,OBC,GENERAL', 'Assam,Meghalaya,Manipur,Mizoram,Nagaland,Tripura,Arunachal Pradesh,Sikkim', 'STUDENT', 'https://scholarships.gov.in', true, '2014-01-01', null, 'Aadhaar Card,Income Certificate,Domicile Certificate,Admission Letter,Marksheet', 'Rs 5400 per month for general courses Rs 7800 for technical courses', 'ONLINE', 'Apply on scholarships.gov.in'),

-- PRIVATE SCHOLARSHIPS
('Tata Capital Pankh Scholarship', 'Tata Capital (Private)', 'Scholarship for students from low income families for higher education', 16, 25, 400000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://www.buddy4study.com/tata-capital-pankh-scholarship', true, '2025-08-01', '2026-09-30', 'Aadhaar Card,Income Certificate,Previous Marksheet,Admission Letter,Bank Passbook', 'Up to Rs 50000 per year for tuition and other education expenses', 'ONLINE', 'Apply on buddy4study.com between August and September'),

('Reliance Foundation Scholarship UG', 'Reliance Foundation (Private)', 'Scholarship for outstanding undergraduate students', 17, 25, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://www.reliancefoundation.org/scholarships', true, '2025-08-01', '2025-10-07', 'Aadhaar Card,Admission Letter,Class 12 Marksheet,Bank Passbook', 'Up to Rs 2 lakh per year plus mentoring and industry exposure', 'ONLINE', 'Apply on reliancefoundation.org between August and October'),

('HDFC Badhte Kadam Scholarship', 'HDFC Bank (Private)', 'Scholarship for students from disadvantaged backgrounds', 15, 25, 250000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://www.hdfcbank.com/personal/borrow/popular-loans/educational-loan/badhte-kadam', true, '2025-08-01', '2026-03-31', 'Aadhaar Card,Income Certificate,Previous Marksheet,Bank Passbook,Admission Letter', 'Up to Rs 1 lakh for all education related expenses', 'ONLINE', 'Apply on HDFC bank website or buddy4study.com'),

('Infosys Foundation STEM Stars', 'Infosys Foundation (Private)', 'Scholarship for female students in STEM courses', 17, 25, 800000, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://www.infosys.com/infosys-foundation', true, '2025-07-01', '2026-01-31', 'Aadhaar Card,Admission Letter,Class 12 Marksheet,Income Certificate', 'Up to Rs 1 lakh per year for female students in engineering science technology', 'ONLINE', 'Apply on Infosys Foundation website'),

('SBI Asha Scholarship', 'SBI Foundation (Private)', 'Scholarship for meritorious students from low income families', 15, 25, 600000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://www.sbifoundation.in', true, '2025-07-01', '2025-11-30', 'Aadhaar Card,Income Certificate,Previous Marksheet,Bank Passbook,Admission Letter', 'Rs 15000 to Rs 20 lakh depending on course and institution', 'ONLINE', 'Apply on SBI Foundation website between July and November'),

('Aditya Birla Scholarship', 'Aditya Birla Group (Private)', 'Scholarship for students in IIT IIM and other top institutions', 17, 25, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://adityabirlascholars.net', true, '2025-08-01', '2025-09-30', 'Aadhaar Card,Admission Letter from IIT/IIM/BITS/Law School,Marksheet', 'Rs 65000 per year for IIT students Rs 175000 for IIM students', 'ONLINE', 'Apply on adityabirlascholars.net after getting admission in top institutes'),

('Bharti Airtel Scholarship', 'Bharti Foundation (Private)', 'Full scholarship for students in top 50 NIRF institutes', 17, 22, 800000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://www.bhartiairtel.in/bharti-foundation', true, '2025-07-01', '2025-10-31', 'Aadhaar Card,Admission Letter from top 50 NIRF institute,Income Certificate,Marksheet', '100% tuition hostel mess fees plus laptop in first year', 'ONLINE', 'Apply through Bharti Foundation website'),

('Buddy4Study India Foundation Scholarship', 'Buddy4Study (Private)', 'Scholarship aggregator platform with multiple scholarships', 14, 30, 600000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://www.buddy4study.com', true, '2025-06-01', null, 'Aadhaar Card,Income Certificate,Marksheet,Bank Passbook', 'Various scholarships ranging from Rs 10000 to Rs 2 lakh', 'ONLINE', 'Register on buddy4study.com and apply for multiple scholarships'),

-- HOUSING SCHEMES
('PM Awas Yojana Urban', 'Ministry of Housing', 'Subsidized housing for urban poor', 18, null, 300000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmaymis.gov.in', true, '2015-06-25', null, 'Aadhaar Card,Income Certificate,Property Documents,Bank Passbook,Passport Photo', 'Interest subsidy up to Rs 2.67 lakh on home loan or direct assistance up to Rs 1.5 lakh', 'BOTH', 'Apply through local municipal office or pmaymis.gov.in'),

('PM Awas Yojana Gramin', 'Ministry of Rural Development', 'Financial assistance for rural house construction', 18, null, 200000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmayg.nic.in', true, '2016-11-20', null, 'Aadhaar Card,BPL Certificate,Bank Passbook,Land Document', 'Rs 1.2 lakh in plains Rs 1.3 lakh in hilly areas directly in bank account', 'OFFLINE', 'Apply through gram panchayat office'),

-- FINANCIAL INCLUSION
('PM Jan Dhan Yojana', 'Ministry of Finance', 'Zero balance bank account for all citizens', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmjdy.gov.in', true, '2014-08-28', null, 'Aadhaar Card or any government ID,Passport Photo', 'Zero balance account RuPay debit card Rs 2 lakh accident insurance Rs 10000 overdraft', 'OFFLINE', 'Visit any bank branch with Aadhaar card'),

('PM Jeevan Jyoti Bima Yojana', 'Ministry of Finance', 'Life insurance at Rs 436 per year', 18, 50, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://jansuraksha.gov.in', true, '2015-05-09', null, 'Aadhaar Card,Bank Account,Mobile Number', 'Rs 2 lakh life insurance cover at premium of Rs 436 per year auto deducted from bank', 'OFFLINE', 'Enroll through any bank where you have account'),

('PM Suraksha Bima Yojana', 'Ministry of Finance', 'Accident insurance at Rs 20 per year', 18, 70, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://jansuraksha.gov.in', true, '2015-05-09', null, 'Aadhaar Card,Bank Account,Mobile Number', 'Rs 2 lakh accidental death Rs 1 lakh partial disability at only Rs 20 per year', 'OFFLINE', 'Enroll through any bank where you have account'),

('Atal Pension Yojana', 'Ministry of Finance', 'Guaranteed pension for unorganized sector workers', 18, 40, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,FARMER,BUSINESS', 'https://npscra.nsdl.co.in', true, '2015-06-01', null, 'Aadhaar Card,Bank Account,Mobile Number', 'Guaranteed pension Rs 1000-5000 per month after age 60 based on contribution', 'OFFLINE', 'Enroll through bank with Aadhaar and bank account'),

('PM Mudra Yojana', 'Ministry of Finance', 'Collateral free business loans up to Rs 10 lakh', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'BUSINESS', 'https://mudra.org.in', true, '2015-04-08', null, 'Aadhaar Card,Business Plan,Bank Statement,Passport Photo', 'Shishu up to Rs 50000 Kishore Rs 50000-5 lakh Tarun Rs 5-10 lakh at low interest', 'OFFLINE', 'Apply at nearest bank NBFC or MFI with business plan'),

('Stand Up India', 'Ministry of Finance', 'Loans for SC ST and women entrepreneurs', 18, null, null, 'ALL', 'SC,ST', 'ALL', 'BUSINESS', 'https://standupmitra.in', true, '2016-04-05', null, 'Aadhaar Card,Caste Certificate,Business Plan,Bank Statement', 'Rs 10 lakh to 1 crore bank loan for setting up new enterprise', 'ONLINE', 'Apply on standupmitra.in or visit bank branch'),

-- SKILL DEVELOPMENT
('PM Kaushal Vikas Yojana 4.0', 'Ministry of Skill Development', 'Free skill training with certificate and placement support', 15, 45, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,STUDENT', 'https://pmkvyofficial.org', true, '2022-01-01', null, 'Aadhaar Card,Bank Passbook,Passport Photo', 'Free training certificate Rs 8000 stipend and placement assistance', 'OFFLINE', 'Register at nearest PMKVY training center'),

('PM Vishwakarma Yojana', 'Ministry of MSME', 'Support for traditional artisans and craftspeople', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,BUSINESS', 'https://pmvishwakarma.gov.in', true, '2023-09-17', null, 'Aadhaar Card,Proof of traditional craft skill,Bank Passbook', 'Rs 15000 toolkit Rs 500 per day training stipend Rs 1 lakh then Rs 2 lakh loan at 5% interest', 'ONLINE', 'Register on pmvishwakarma.gov.in through CSC'),

('PMEGP', 'Ministry of MSME', 'Subsidy for setting up micro enterprises', 18, 35, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'BUSINESS,OTHER', 'https://kviconline.gov.in', true, '2008-08-15', null, 'Aadhaar Card,Project Report,Qualification Certificate,Caste Certificate if applicable', '15-35% subsidy on project cost up to Rs 50 lakh for manufacturing Rs 20 lakh for services', 'ONLINE', 'Apply on kviconline.gov.in with project report'),

('Deen Dayal Upadhyaya Grameen Kaushalya', 'Ministry of Rural Development', 'Free skill training for rural BPL youth with placement', 15, 35, 200000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,STUDENT', 'https://ddugky.gov.in', true, '2014-09-25', null, 'Aadhaar Card,BPL Certificate,Bank Passbook,Passport Photo', 'Free residential training placement guarantee post placement support for 1 year', 'OFFLINE', 'Contact nearest DDU-GKY training partner'),

-- WOMEN EMPOWERMENT
('Beti Bachao Beti Padhao', 'Ministry of WCD', 'Girl child education and welfare scheme', 0, 18, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://wcd.nic.in', true, '2015-01-22', null, 'Birth Certificate,Aadhaar Card,Parents Aadhaar', 'Awareness benefits conditional cash in some states improved welfare services', 'OFFLINE', 'Contact nearest Anganwadi center'),

('Sukanya Samridhi Yojana', 'Ministry of Finance', 'High interest savings for girl child education and marriage', 0, 10, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://nsiindia.gov.in', true, '2015-01-22', null, 'Girl Birth Certificate,Parents Aadhaar,Address Proof', '8.2% interest rate tax free maturity amount for education or marriage at age 21', 'OFFLINE', 'Open account at post office or authorized bank before girl turns 10'),

('PM Matru Vandana Yojana', 'Ministry of WCD', 'Cash incentive for pregnant and lactating mothers', 19, null, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmmvy.wcd.gov.in', true, '2017-01-01', null, 'Aadhaar Card,Bank Passbook,MCP Card,Mobile Number', 'Rs 5000 in 3 installments for first live birth Rs 6000 for second if girl child', 'OFFLINE', 'Register with ASHA worker or Anganwadi within 150 days of pregnancy'),

('One Stop Centre Sakhi', 'Ministry of WCD', 'Support for women affected by violence', 18, null, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://wcd.nic.in', true, '2015-04-01', null, 'No documents required for emergency help', 'Free shelter medical legal police and psychological support for women in distress', 'OFFLINE', 'Call helpline 181 or visit nearest Sakhi center'),

('PM Ujjwala Yojana 2.0', 'Ministry of Petroleum', 'Free LPG connection for BPL women', 18, null, 200000, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmuy.gov.in', true, '2021-08-10', null, 'Aadhaar Card,BPL Ration Card,Bank Passbook,Passport Photo', 'Free LPG connection with first refill free and stove deposit waived', 'OFFLINE', 'Apply at nearest LPG distributor with BPL card'),

-- ELDERLY AND DISABILITY
('Indira Gandhi Old Age Pension', 'Ministry of Rural Development', 'Monthly pension for BPL elderly citizens', 60, null, 150000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://nsap.nic.in', true, '1995-08-15', null, 'Aadhaar Card,Age Proof,BPL Certificate,Bank Passbook', 'Rs 200-500 per month pension directly in bank account', 'OFFLINE', 'Apply at gram panchayat or municipality office'),

('Indira Gandhi Widow Pension', 'Ministry of Rural Development', 'Monthly pension for BPL widows', 40, 79, 150000, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://nsap.nic.in', true, '1995-08-15', null, 'Aadhaar Card,Husband Death Certificate,BPL Certificate,Bank Passbook', 'Rs 300 per month pension directly in bank account', 'OFFLINE', 'Apply at gram panchayat or municipality office'),

('Indira Gandhi Disability Pension', 'Ministry of Rural Development', 'Monthly pension for severely disabled BPL persons', 18, 79, 150000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://nsap.nic.in', true, '2009-11-01', null, 'Aadhaar Card,Disability Certificate 80% or more,BPL Certificate,Bank Passbook', 'Rs 300 per month pension for persons with 80% or more disability', 'OFFLINE', 'Apply at gram panchayat or municipality office'),

('Unique Disability ID UDID', 'Ministry of Social Justice', 'Disability ID card for accessing all disability benefits', 0, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://swavlambancard.gov.in', true, '2016-06-01', null, 'Aadhaar Card,Disability Certificate from government hospital,Passport Photo', 'UDID card to access all disability schemes and reservations in one place', 'ONLINE', 'Apply on swavlambancard.gov.in'),

-- RURAL EMPLOYMENT
('Mahatma Gandhi NREGA', 'Ministry of Rural Development', '100 days guaranteed wage employment for rural households', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,FARMER', 'https://nrega.nic.in', true, '2006-02-02', null, 'Aadhaar Card,Bank Passbook,Job Card', 'Minimum 100 days wage employment per year at Rs 230-400 per day based on state', 'OFFLINE', 'Register at gram panchayat to get job card then demand work'),

-- FOOD SECURITY
('PM Garib Kalyan Anna Yojana', 'Ministry of Consumer Affairs', 'Free food grain for poor families', 18, null, 150000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://dfpd.gov.in', true, '2020-03-26', null, 'Ration Card,Aadhaar Card', '5 kg free food grain per person per month under National Food Security Act', 'OFFLINE', 'Collect from nearest ration shop with ration card'),

-- ANNAPURNA
('Annapurna Scheme', 'Ministry of Rural Development', 'Free food grain for senior citizens not covered by pension', 65, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://dfpd.gov.in', true, '2000-04-01', null, 'Aadhaar Card,Age Proof', '10 kg free food grain per month for eligible senior citizens', 'OFFLINE', 'Apply at gram panchayat or district food office'),

-- DIGITAL AND STARTUP
('Startup India Seed Fund', 'Ministry of Commerce', 'Funding support for early stage startups', 18, 45, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'BUSINESS', 'https://startupindia.gov.in', true, '2021-04-01', null, 'Aadhaar Card,DPIIT Registration,Business Plan,Bank Account', 'Up to Rs 20 lakh grant and Rs 50 lakh convertible debentures for startups', 'ONLINE', 'Register on startupindia.gov.in and apply for seed fund'),

('PM SVANidhi', 'Ministry of Housing', 'Working capital loan for street vendors', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'BUSINESS,OTHER', 'https://pmsvanidhi.mohua.gov.in', true, '2020-06-01', null, 'Aadhaar Card,Vending Certificate or Letter of Recommendation,Bank Passbook', 'Rs 10000 then Rs 20000 then Rs 50000 collateral free loan at subsidized interest', 'ONLINE', 'Apply on pmsvanidhi.mohua.gov.in or through urban local body'),

-- SC ST SPECIAL
('Venture Capital Fund for SC', 'Ministry of Social Justice', 'Equity funding for SC entrepreneurs', 18, null, null, 'ALL', 'SC', 'ALL', 'BUSINESS', 'https://socialjustice.gov.in', true, '2014-01-01', null, 'Aadhaar Card,Caste Certificate,Business Plan,Company Registration', 'Concessional finance up to Rs 15 lakh at 4% interest for SC entrepreneurs', 'OFFLINE', 'Contact National Scheduled Castes Finance Corporation'),

('National Overseas Scholarship SC ST', 'Ministry of Social Justice', 'Scholarship for SC ST students to study abroad', 18, 35, 600000, 'ALL', 'SC,ST', 'ALL', 'STUDENT', 'https://nosmsje.gov.in', true, '2022-01-01', null, 'Aadhaar Card,Caste Certificate,Admission Letter from foreign university,Income Certificate', 'Full financial support for masters and PhD abroad including tuition living expenses airfare', 'ONLINE', 'Apply on nosmsje.gov.in when notification released'),

('Eklavya Residential School Scheme', 'Ministry of Tribal Affairs', 'Free residential school for ST students in tribal areas', 6, 18, null, 'ALL', 'ST', 'ALL', 'STUDENT', 'https://tribal.nic.in', true, '1998-01-01', null, 'Aadhaar Card,Caste Certificate,Birth Certificate', 'Free quality residential education from class 6 to 12 with all facilities', 'OFFLINE', 'Apply through nearest EMRS school or tribal welfare office');

INSERT IGNORE INTO schemes (name, ministry, description, min_age, max_age, max_income, eligible_gender, eligible_castes, eligible_states, eligible_occupations, apply_url, is_active, start_date, end_date, required_documents, benefits, application_mode, application_process) VALUES

-- UNORGANIZED WORKERS
('e-Shram Card', 'Ministry of Labour', 'Universal identity card for unorganized workers with accident insurance', 16, 59, 180000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,FARMER', 'https://eshram.gov.in', true, '2021-08-26', null, 'Aadhaar Card,Bank Passbook,Mobile Number linked to Aadhaar', 'Free e-Shram card with Rs 2 lakh accident insurance and access to 12+ government schemes', 'ONLINE', 'Register free on eshram.gov.in or nearest CSC center in 5 minutes'),

('PM Shram Yogi Maandhan', 'Ministry of Labour', 'Pension scheme for unorganized sector workers - rickshaw pullers street vendors mazdoor', 18, 40, 180000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,FARMER', 'https://maandhan.in', true, '2019-02-15', null, 'Aadhaar Card,Bank Passbook,Mobile Number', 'Rs 3000 per month guaranteed pension after age 60 government matches your contribution', 'OFFLINE', 'Enroll at nearest CSC center with Aadhaar and bank passbook'),

('Building Construction Workers Welfare', 'Ministry of Labour', 'Welfare benefits for construction workers registered with BOCW board', 18, 60, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER', 'https://bocw.gov.in', true, '1996-08-19', null, 'Aadhaar Card,Proof of construction work for 90 days,Bank Passbook,Passport Photo', 'Pension accident insurance maternity benefit education scholarship housing loan and more', 'OFFLINE', 'Register at state BOCW welfare board office with proof of 90 days construction work'),

('National Career Service Portal', 'Ministry of Labour', 'Free government job portal connecting job seekers with employers', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,STUDENT', 'https://ncs.gov.in', true, '2015-07-20', null, 'Aadhaar Card,Educational Certificates', 'Free job matching career counseling skill courses and employment fair notifications', 'ONLINE', 'Register free on ncs.gov.in and upload resume'),

('Employment Linked Incentive Scheme', 'Ministry of Labour', 'Rs 15000 for first time employees joining formal workforce', 18, 35, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'SALARIED', 'https://labour.gov.in', true, '2024-08-01', null, 'Aadhaar Card,EPFO UAN Number,Bank Passbook', 'One month salary up to Rs 15000 for first time EPFO registered employees', 'ONLINE', 'Employer registers on EPFO portal benefit credited automatically'),

-- MINORITIES
('Pre Matric Minority Scholarship', 'Ministry of Minority Affairs', 'Scholarship for minority students in class 1 to 10', 6, 16, 100000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2022-07-01', '2026-10-31', 'Aadhaar Card,Minority Community Certificate,Income Certificate,Previous Marksheet,Bank Passbook', 'Rs 1000-7000 per year for minority students in class 1 to 10', 'ONLINE', 'Apply on scholarships.gov.in before October 31'),

('Post Matric Minority Scholarship', 'Ministry of Minority Affairs', 'Scholarship for minority students after class 10', 15, 30, 200000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2022-07-01', '2026-10-31', 'Aadhaar Card,Minority Community Certificate,Income Certificate,Previous Marksheet,Bank Passbook,Bonafide Certificate', 'Up to Rs 3000 per year maintenance plus course fees for post matric minority students', 'ONLINE', 'Apply on scholarships.gov.in before October 31'),

('Naya Savera Free Coaching', 'Ministry of Minority Affairs', 'Free coaching for minority students for competitive exams UPSC SSC IIT', 18, 35, 600000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://minorityaffairs.gov.in', true, '2009-01-01', null, 'Aadhaar Card,Minority Certificate,Income Certificate,Educational Qualification', 'Free coaching for government exams UPSC SSC banking technical courses with stipend', 'OFFLINE', 'Contact nearest Naya Savera coaching center or apply through minority affairs ministry'),

('Nai Udaan UPSC Support', 'Ministry of Minority Affairs', 'Financial support for minority students who clear UPSC SSC prelims', 21, 35, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://minorityaffairs.gov.in', true, '2014-01-01', null, 'Aadhaar Card,Minority Certificate,UPSC/SSC Prelims Result,Bank Passbook', 'Rs 65000 per year for UPSC mains preparation for minority students clearing prelims', 'ONLINE', 'Apply through National Minorities Development and Finance Corporation'),

('PM VIKAS Skill Minorities', 'Ministry of Minority Affairs', 'Free skill training and entrepreneurship for minority youth', 14, 35, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,STUDENT', 'https://minorityaffairs.gov.in', true, '2023-01-01', null, 'Aadhaar Card,Minority Certificate,Educational Certificate', 'Free skill training in modern trades with placement support and entrepreneurship development', 'OFFLINE', 'Contact nearest PM VIKAS training center through minority affairs ministry'),

('NMDFC Loan Minorities', 'Ministry of Minority Affairs', 'Concessional loans for self employment for minority communities', 18, 55, 600000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'BUSINESS,OTHER', 'https://nmdfc.org', true, '1994-09-01', null, 'Aadhaar Card,Minority Certificate,Income Certificate,Business Plan,Bank Passbook', 'Loans up to Rs 20 lakh at 6% interest rate for business education and housing for minorities', 'OFFLINE', 'Apply through State Channelising Agency or NMDFC website'),

('Nai Roshni Minority Women', 'Ministry of Minority Affairs', 'Leadership development program for minority women', 18, 65, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://minorityaffairs.gov.in', true, '2012-01-01', null, 'Aadhaar Card,Minority Certificate', 'Free training in leadership communication legal rights financial literacy for minority women', 'OFFLINE', 'Contact nearest NGO implementing Nai Roshni or apply through minority affairs ministry'),

('Maulana Azad National Fellowship', 'Ministry of Minority Affairs', 'Fellowship for minority students pursuing MPhil and PhD', 21, 40, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://minorityaffairs.gov.in', true, '2009-04-01', null, 'Aadhaar Card,Minority Certificate,Admission Letter,Marksheet', 'Fellowship stipend for minority research scholars', 'ONLINE', 'Apply through UGC portal when notified'),

-- DISABILITY SCHEMES
('ADIP Assistive Devices', 'Ministry of Social Justice', 'Free assistive devices for disabled persons - wheelchair hearing aid tricycle', 0, null, 200000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://alimco.in', true, '1981-01-01', null, 'Aadhaar Card,Disability Certificate 40% or more,Income Certificate,Passport Photo', 'Free wheelchair tricycle hearing aid artificial limbs crutches visual aids worth Rs 10000-1 lakh', 'OFFLINE', 'Apply at ALIMCO camp or nearest district rehabilitation center'),

('Scholarship for Disabled Students', 'Ministry of Social Justice', 'Scholarship for students with disabilities', 6, 30, 250000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'STUDENT', 'https://scholarships.gov.in', true, '2014-01-01', null, 'Aadhaar Card,Disability Certificate 40%,Income Certificate,Previous Marksheet,Bank Passbook', 'Rs 1200 per month stipend plus extra coaching allowance for disabled students', 'ONLINE', 'Apply on scholarships.gov.in under disabled category'),

('National Handicapped Finance Corporation Loan', 'Ministry of Social Justice', 'Concessional loans for disabled persons for self employment', 18, 55, 300000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'BUSINESS,OTHER', 'https://nhfdc.nic.in', true, '1997-01-01', null, 'Aadhaar Card,Disability Certificate 40%,Income Certificate,Business Plan,Bank Passbook', 'Loans up to Rs 25 lakh at 5% interest for disabled persons for business education housing', 'OFFLINE', 'Apply through State Channelising Agency or NHFDC'),

('Divyangjan Sports Award', 'Ministry of Sports', 'Financial support and recognition for disabled athletes', 10, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER', 'https://yas.nic.in', true, '2000-01-01', null, 'Aadhaar Card,Disability Certificate,Sports Achievement Certificate', 'Cash award Rs 5-75 lakh for para athletes representing India in national international events', 'OFFLINE', 'Apply through state sports authority or Paralympic committee'),

-- NEWLY LAUNCHED 2024-2025
('PM Surya Ghar Muft Bijli', 'Ministry of New and Renewable Energy', 'Free solar rooftop installation with 300 units free electricity per month', 18, null, 150000, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'ALL', 'https://pmsuryagarh.gov.in', true, '2024-02-15', null, 'Aadhaar Card,Electricity Bill,Bank Passbook,Property Document', '300 units free electricity per month after rooftop solar installation subsidy up to Rs 78000', 'ONLINE', 'Apply on pmsuryagarh.gov.in and select empanelled vendor'),

('Vishwakarma Credit Guarantee', 'Ministry of MSME', 'Credit guarantee for traditional craftsmen and artisans', 18, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'ALL', 'OTHER,BUSINESS', 'https://pmvishwakarma.gov.in', true, '2023-09-17', null, 'Aadhaar Card,PM Vishwakarma Registration,Bank Passbook', 'Collateral free loan Rs 1 lakh then Rs 2 lakh at 5% interest with credit guarantee', 'ONLINE', 'First register on pmvishwakarma.gov.in then apply for loan through bank');

UPDATE schemes SET eligible_religions = 'MUSLIM,CHRISTIAN,SIKH,BUDDHIST,JAIN' WHERE name IN ('Pre Matric Minority Scholarship', 'Post Matric Minority Scholarship', 'Naya Savera Free Coaching', 'Nai Udaan UPSC Support', 'PM VIKAS Skill Minorities', 'NMDFC Loan Minorities', 'Nai Roshni Minority Women', 'Maulana Azad National Fellowship');

INSERT IGNORE INTO schemes (name, ministry, description, min_age, max_age, max_income, eligible_gender, eligible_castes, eligible_states, eligible_occupations, apply_url, is_active, start_date, end_date, required_documents, benefits, application_mode, application_process, eligible_religions) VALUES
('UP Kanya Sumangala Yojana', 'UP Government', 'Financial support for girl child in UP', 0, 18, 300000, 'FEMALE', 'SC,ST,OBC,GENERAL', 'Uttar Pradesh', 'ALL', 'https://mksy.up.gov.in', true, '2019-04-01', null, 'Aadhaar Card,Birth Certificate,Bank Passbook,Income Certificate', 'Rs 15000 in 6 installments from birth to class 12 for girl child in UP', 'ONLINE', 'Apply on mksy.up.gov.in', 'ALL'),
('UP Mukhyamantri Abhyudaya Yojana', 'UP Government', 'Free UPSC IAS PCS coaching for UP students', 18, 35, null, 'ALL', 'SC,ST,OBC,GENERAL', 'Uttar Pradesh', 'STUDENT', 'https://abhyuday.up.gov.in', true, '2021-02-16', null, 'Aadhaar Card,Domicile Certificate,Educational Certificate', 'Free coaching for UPSC IAS PCS NDA CDS JEE NEET with study material', 'ONLINE', 'Apply on abhyuday.up.gov.in', 'ALL'),
('UP Berojgari Bhatta', 'UP Government', 'Unemployment allowance for educated UP youth', 18, 35, null, 'ALL', 'SC,ST,OBC,GENERAL', 'Uttar Pradesh', 'OTHER,STUDENT', 'https://sewayojan.up.nic.in', true, '2019-01-01', null, 'Aadhaar Card,Domicile Certificate,Educational Certificate,Bank Passbook', 'Rs 1000-1500 per month unemployment allowance for graduate postgraduate youth in UP', 'ONLINE', 'Register on sewayojan.up.nic.in', 'ALL'),
('UP Vridha Pension Yojana', 'UP Government', 'Old age pension for elderly in UP', 60, null, 200000, 'ALL', 'SC,ST,OBC,GENERAL', 'Uttar Pradesh', 'ALL', 'https://sspy-up.gov.in', true, '2016-01-01', null, 'Aadhaar Card,Age Proof,Bank Passbook,Income Certificate', 'Rs 1000 per month pension for elderly above 60 in UP', 'ONLINE', 'Apply on sspy-up.gov.in', 'ALL'),
('Bihar Student Credit Card', 'Bihar Government', 'Education loan up to Rs 4 lakh for Bihar students', 18, 25, null, 'ALL', 'SC,ST,OBC,GENERAL', 'Bihar', 'STUDENT', 'https://7nischay-yuvaupmission.bihar.gov.in', true, '2016-10-02', null, 'Aadhaar Card,Domicile Certificate,Admission Letter,Class 12 Marksheet,Bank Passbook', 'Education loan up to Rs 4 lakh at 4% interest for boys 1% for girls', 'ONLINE', 'Apply on 7nischay portal', 'ALL'),
('Bihar Mukhyamantri Kanya Utthan Yojana', 'Bihar Government', 'Financial incentive for girl child education in Bihar', 0, 25, null, 'FEMALE', 'SC,ST,OBC,GENERAL', 'Bihar', 'STUDENT', 'https://edudbt.bih.nic.in', true, '2019-04-01', null, 'Aadhaar Card,Birth Certificate,Bank Passbook,Educational Certificate', 'Rs 50000 total incentive from birth to graduation for girl child in Bihar', 'ONLINE', 'Apply through school or edudbt.bih.nic.in', 'ALL'),
('Rajasthan Mukhyamantri Chiranjeevi Yojana', 'Rajasthan Government', 'Free health insurance for all Rajasthan families', 0, null, null, 'ALL', 'SC,ST,OBC,GENERAL', 'Rajasthan', 'ALL', 'https://chiranjeevi.rajasthan.gov.in', true, '2021-05-01', null, 'Aadhaar Card,Jan Aadhaar Card', 'Free health insurance up to Rs 25 lakh per year for all Rajasthan families', 'ONLINE', 'Register on chiranjeevi.rajasthan.gov.in', 'ALL'),
('MP Mukhyamantri Medhavi Vidyarthi Yojana', 'MP Government', 'Free higher education for meritorious MP students', 17, 25, 600000, 'ALL', 'SC,ST,OBC,GENERAL', 'Madhya Pradesh', 'STUDENT', 'https://medhavikalyan.mp.gov.in', true, '2017-06-01', null, 'Aadhaar Card,Class 12 Marksheet 70% or above,Income Certificate,Admission Letter', 'Full tuition fee paid by MP government for students scoring 70% in class 12', 'ONLINE', 'Apply on medhavikalyan.mp.gov.in', 'ALL'),
('West Bengal Kanyashree Prakalpa', 'WB Government', 'Scholarship for girl students in West Bengal', 13, 18, 120000, 'FEMALE', 'SC,ST,OBC,GENERAL', 'West Bengal', 'STUDENT', 'https://wbkanyashree.gov.in', true, '2013-10-01', null, 'Aadhaar Card,Income Certificate,School Certificate,Bank Passbook', 'Rs 1000 per year annual scholarship and Rs 25000 one time grant for girls in WB', 'ONLINE', 'Apply through school on wbkanyashree.gov.in', 'ALL'),
('Maharashtra Swadhar Gruh Scheme', 'Maharashtra Government', 'Free hostel and financial aid for SC students in Maharashtra', 15, 30, 250000, 'ALL', 'SC', 'Maharashtra', 'STUDENT', 'https://sjsa.maharashtra.gov.in', true, '2016-01-01', null, 'Aadhaar Card,Caste Certificate,Income Certificate,Admission Letter,Bank Passbook', 'Rs 51000 per year for boarding lodging and education for SC students in Maharashtra', 'ONLINE', 'Apply through district social welfare office', 'ALL');

-- Update end_dates for deadline testing (within 60 days of May 27, 2026)
UPDATE schemes SET end_date = '2026-06-15' WHERE name = 'Bihar Student Credit Card';
UPDATE schemes SET end_date = '2026-07-20' WHERE name = 'UP Mukhyamantri Abhyudaya Yojana';

